# Generated by Django 3.2 on 2021-04-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210416_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
